// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7GNfvTVnEifIZ9AqA048lJepYkzbZ2o',
    appId: '1:209438261913:web:6435ae978d19b293622e08',
    messagingSenderId: '209438261913',
    projectId: 'notes-app-flutter-bc31b',
    authDomain: 'notes-app-flutter-bc31b.firebaseapp.com',
    storageBucket: 'notes-app-flutter-bc31b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChqu8YZeGy54H3jy97VWV-Ze-MwoYktZQ',
    appId: '1:209438261913:android:a8e65b10b7d65d75622e08',
    messagingSenderId: '209438261913',
    projectId: 'notes-app-flutter-bc31b',
    storageBucket: 'notes-app-flutter-bc31b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1JWzY4X2hVcWfvCwlJD2zPmqi9FgW640',
    appId: '1:209438261913:ios:10a3a6b272589b17622e08',
    messagingSenderId: '209438261913',
    projectId: 'notes-app-flutter-bc31b',
    storageBucket: 'notes-app-flutter-bc31b.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1JWzY4X2hVcWfvCwlJD2zPmqi9FgW640',
    appId: '1:209438261913:ios:10a3a6b272589b17622e08',
    messagingSenderId: '209438261913',
    projectId: 'notes-app-flutter-bc31b',
    storageBucket: 'notes-app-flutter-bc31b.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF7GNfvTVnEifIZ9AqA048lJepYkzbZ2o',
    appId: '1:209438261913:web:1c9ea39728d96dc0622e08',
    messagingSenderId: '209438261913',
    projectId: 'notes-app-flutter-bc31b',
    authDomain: 'notes-app-flutter-bc31b.firebaseapp.com',
    storageBucket: 'notes-app-flutter-bc31b.firebasestorage.app',
  );
}
